# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StackNavigatorNa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StackNavigatorNa

  target 'StackNavigatorNa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'StackNavigatorNaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
